.PHONY: clean All

All:
	@echo "----------Building project:[ CTestTest - Debug ]----------"
	@cd "CTestTest" && "$(MAKE)" -f  "CTestTest.mk"
clean:
	@echo "----------Cleaning project:[ CTestTest - Debug ]----------"
	@cd "CTestTest" && "$(MAKE)" -f  "CTestTest.mk" clean
