.PHONY: clean All

All:
	@echo "----------Building project:[ CControlFlow - Debug ]----------"
	@cd "CControlFlow" && "$(MAKE)" -f  "CControlFlow.mk"
clean:
	@echo "----------Cleaning project:[ CControlFlow - Debug ]----------"
	@cd "CControlFlow" && "$(MAKE)" -f  "CControlFlow.mk" clean
