.PHONY: clean All

All:
	@echo "----------Building project:[ COperators - Debug ]----------"
	@cd "COperators" && "$(MAKE)" -f  "COperators.mk"
clean:
	@echo "----------Cleaning project:[ COperators - Debug ]----------"
	@cd "COperators" && "$(MAKE)" -f  "COperators.mk" clean
