.PHONY: clean All

All:
	@echo "----------Building project:[ CreateProgram - Debug ]----------"
	@cd "CreateProgram" && "$(MAKE)" -f  "CreateProgram.mk"
clean:
	@echo "----------Cleaning project:[ CreateProgram - Debug ]----------"
	@cd "CreateProgram" && "$(MAKE)" -f  "CreateProgram.mk" clean
