.PHONY: clean All

All:
	@echo "----------Building project:[ ErrorsProgram - Debug ]----------"
	@cd "ErrorsProgram" && "$(MAKE)" -f  "ErrorsProgram.mk"
clean:
	@echo "----------Cleaning project:[ ErrorsProgram - Debug ]----------"
	@cd "ErrorsProgram" && "$(MAKE)" -f  "ErrorsProgram.mk" clean
